#!/usr/bin/env bash
# /etc/initcpio/install/encrypt-auto

# ------------------------------------------------------------------------------
#                                                                              -
#  Created by Fonic <https://github.com/fonic>                                 -
#  Date: 04/16/23 - 07/20/25                                                   -
#                                                                              -
#  Based on:                                                                   -
#  /usr/lib/initcpio/install/encrypt (stock LUKS hook)                         -
#                                                                              -
# ------------------------------------------------------------------------------

build() {
    local mod

    add_module 'dm-crypt'
    add_module 'dm-integrity'
    if [[ $CRYPTO_MODULES ]]; then
        for mod in $CRYPTO_MODULES; do
            add_module "$mod"
        done
    else
        add_all_modules '/crypto/'
    fi

    add_binary 'cryptsetup'

    # Required for renaming of mapper devices (mkinitcpio's busybox, '/lib/
    # initcpio/busybox', does not include the 'find' applet, thus GNU find
    # is being included)
    add_binary 'dmsetup'
    add_binary 'find'

    # Required for checking if plymouth is running in the background
    add_binary 'pidof'

    map add_udev_rule \
        '10-dm.rules' \
        '13-dm-disk.rules' \
        '95-dm-notify.rules' \
        '/usr/lib/initcpio/udev/11-dm-initramfs.rules'

    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
    add_binary '/usr/lib/libgcc_s.so.1'

    # cryptsetup loads the legacy provider which is required for whirlpool
    add_binary '/usr/lib/ossl-modules/legacy.so'

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows for encrypted devices (root, swap and other volumes) to be
unlocked during boot. All devices of type 'crypto_LUKS' will be unlocked as
'/dev/mapper/luks-<UUID>'. After unlocking, mapper devices with volume labels
will be renamed to '/dev/mapper/luks-<LABEL>' for convenience.

You will be prompted for the password at runtime. This means you must have a
keyboard available to input it, and you may need the keymap hook as well to
ensure that the keyboard is using the layout you expect.

There are no configuration options.
HELPEOF
}
